### ISSUE TITLE
Typo in error message: The Transaction has wrong format or unexpcted...

### ISSUE THREAD

**Issue by rnnz** [parallelchain-io/pchain-sdk#10]
Environment: Windows, Linux

How to produce:
- Run a pchain command:
```
pchain.exe submit tx --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data "hello_contract.wasm" --nonce 1 --keypair-name keypair.json
```

- Error mesage:
```
The Transaction has wrong format or unexpcted problem encountered. The transaction is not sent.
```

- Typo: `unexpcted`

**Comment by parallelchainlab** [comment]
Thanks for your reporting.

The latest version of pchain_client binary can be downloaded, includuing the mentioned fixes.

(as of 21-Nov)

### Windows
https://cms.parallelchain.io/parallelchain-client_v0.3.1_win.zip
### Linux
https://cms.parallelchain.io/parallelchain-client_v0.3.1_linux.tar.xz
### Mac
https://cms.parallelchain.io/parallelchain-client_v0.3.1_mac.tar.xz
