### ISSUE TITLE
Tokens built on Xpll

### ISSUE THREAD

**Issue by kbndz123** [parallelchain-io/pchain-sdk#12]
Not a major issue, but when signing into the wallet, I've noticed you have to reintegrate tokens built upon xpll into the wallet or they don't display the balance. Not an issue per say, but if it automatically did this when signing the experience would've been a little smoother.

**Comment by AlvinHon** [comment]
This comment belongs to old version on testnet. 

But thanks for your comment. Please try on our new testnet!
 https://explorer.parallelchain.io/explorer?network=Testnet
