### ISSUE TITLE
Withdrawl of staked tokens

### ISSUE THREAD

**Issue by kbndz123** [parallelchain-io/pchain-sdk#13]
noticed when I attempted to withdraw tokens from the staking pool I set it to withdraw 666 tokens and it claimed it was successful then proceeded to withdraw 0 tokens

**Comment by AlvinHon** [comment]
This comment belongs to old version on testnet.

But thanks for your comment. Please try on our new testnet!
https://explorer.parallelchain.io/explorer?network=Testnet

Furthermore, the staking mechanism  is completely different. More information on https://docs.parallelchain.io
