### ISSUE TITLE
keypair.json not created

### ISSUE THREAD

**Issue by andsch23** [parallelchain-io/pchain-sdk#14]
keypair.json will not be created in Windows or where I can find the file?

**Comment by parallelchainlab** [comment]
In Windows, the keypair.json can be found on home directory of your user account. For example, "C:\Users\user\\.parallelchain\pchain_cli\keypair.json"

Reference:
https://docs.parallelchain.io/getting_started/installation/#for-windows

**Comment by andsch23** [comment]
Thank you
