### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by andsch23** [parallelchain-io/pchain-sdk#15]
checking transaction history in Windows via cmd show this error when in Tx Hash first sign is an '-' :

pchain_client.exe query blocks --tx-hash -vzIhAd2u0H6ls8NECgMkOEbYuPoWJA2NWlToXjTnS8 --limit 1 --order desc
error: Found argument '-v' which wasn't expected, or isn't valid in this context

        If you tried to supply `-v` as a value rather than a flag, use `-- -v`

**Comment by AlvinHon** [comment]
This comment belongs to old version on testnet.

But thanks for your comment. Please try our new version 'pchain_client'! https://github.com/parallelchain-io/pchain-client-cli

Feel free to raise issue on that repository as well.
