### ISSUE TITLE
Contract Deployment

### ISSUE THREAD

**Issue by andsch23** [parallelchain-io/pchain-sdk#17]
Contract Deploy was correct:
pchain_client.exe submit tx --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data .\MentaLeaves.wasm --nonce 2 --keypair-name swansch
Contract address: "puGAAdSqbNjTskZDvPL9kwpF-pbENldGEP_upbD2q4w"
Signature of tx: "aYUCGA2-lNfTrYLMb5bRDoc4MdDFxN430EZyP0XaEMaFySBkz_b4VwGaxfY1orSFjWaz0pCCMkUBQfMFg6atBA"
Hash of tx: "PkA_WfO4NoxxWICNacfkq7UXQepG9mIsnzAQIgF1f0o"
Submit Transaction {
  "to_address": "null",
  "value": 0,
  "tip": 0,
  "gas_limit": 10000000,
  "gas_price": 1,
  "data": ".\\MentaLeaves.wasm",
  "deploy_args": "",
  "nonce": 2,
  "keypair_name": "swansch"
}
Status 202
Response "Transaction Added to mempool"

But I don't get a stream of bytes in the terminal through the contract-code flag:
pchain_client.exe query blocks --tx-hash PkA_WfO4NoxxWICNacfkq7UXQepG9mIsnzAQIgF1f0o --limit 1 --order desc
Query Error. Status: 404 Not Found
Query Error. Detail:
Database query error.Please provide the correct set of Query Parameters and Filters

**Comment by AlvinHon** [comment]
This comment belongs to old version on testnet.

But thanks for your comment. Please try on our new testnet!
https://explorer.parallelchain.io/explorer?network=Testnet

And also the CLI 'pchain_client', 

https://github.com/parallelchain-io/pchain-client-cli

FYI, you can find the user guide on https://docs.parallelchain.io
