### ISSUE TITLE
Compiler error pchain_compile

### ISSUE THREAD

**Issue by baokhanh2021** [parallelchain-io/pchain-sdk#5]
Compiler error pchain_compile
I downloaded the installer but it didn't work, I clicked on pchain_compile windown asked to agree to the installation and then exited it shows nothing but it's nowhere to be found

**Comment by aegiszzz** [comment]
will any guide be published for testnet

**Comment by parallelchainlab** [comment]
You can download `pchain_complie` from provided shared folder on Google Drive. There are only executable but not installer. Please make sure to download the correct binaries that matches your operation system (macOS, Ubuntu or Windows ).

Usage of `pchain_compile` is almost as same as previous version. Please check the [guide](https://docs.parallelchain.io/smart_contract_sdk/build_contract/) from testnet 2.
