### ISSUE TITLE
Missing pchain_client.exe for Windows

### ISSUE THREAD

**Issue by rnnz** [parallelchain-io/pchain-sdk#6]
Can't find `pchain_client.exe` for Windows in the shared folder https://drive.google.com/drive/folders/1hNNY0hzK6CdmrL6K0cttDXUnpRCP_jz4

**Comment by rnnz** [comment]
It could be `pchain.exe`. I found that command in some documentations, but can't find that tool.

**Comment by rnnz** [comment]
Update: I can download from https://docs.parallelchain.io/, but I'm not sure it's the latest version.

**Comment by parallelchainlab** [comment]
Thanks for your comment. We provide an alternative download link to latest windows version of `pchain_client`. Please check the Google drive, or try https://cms.parallelchain.io/uploads/pchain_client_251e1faf3b.exe

**Comment by parallelchainlab** [comment]
Thanks for comment. We provide an alternative download link to windows version of `pchain_client`. Please check the shared folder, or try https://cms.parallelchain.io/uploads/pchain_client_251e1faf3b.exe

**Comment by rnnz** [comment]
I can download and run the command now. Thanks!
