### ISSUE TITLE
Submit Error. Status: 422: Failed to deserialize the input as a ParallelChain Mainnet Transaction

### ISSUE THREAD

**Issue by rnnz** [parallelchain-io/pchain-sdk#7]
- Environment: Windows
- Config.json:
```
{
  "analytics_api_url": "https://node-t3-1.digital-transaction.net/analytics",
  "target_url": "https://node-t3-1.digital-transaction.net",
  "rich_api_url": "https://node-t3-1.digital-transaction.net:33356"
}
```
- Command: 
`pchain.exe submit tx --from-address pxSk6-3pl_yOFe95bwLDuETle8unlR6971A6SwqO3hI --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data "./hello_contract.wasm" --nonce 1 --path-to-keypair-json ./keypair.json`
- Output:
```
Contract address: "nQqehnERYZlDvp_jDInnQCLOG1gjK-MzMSJ-lCebR-Q"
Signature of tx: "OQVeCBVtoajf_2Z8uyv9WCZBz99EzHfVH1gwZQtSZDhgNmfP-WrW7HdTMiqg3U0MKkZwgjJHDiWi35BpGaF5Aw"
Hash of tx: "DxcMGhxzXYOyRURqda_E3wf-NiBPsqRr-OWIELaGR0k"
Submit Transaction {
  "from_address": "pxSk6-3pl_yOFe95bwLDuETle8unlR6971A6SwqO3hI",
  "to_address": "null",
  "value": 0,
  "tip": 0,
  "gas_limit": 10000000,
  "gas_price": 1,
  "data": "./hello_contract.wasm",
  "deploy_args": "",
  "nonce": 1,
  "path_to_keypair_json": "./keypair.json"
}
Submit Error. Status: 422
Submit Error. Detail: Failed to deserialize the input as a ParallelChain Mainnet Transaction
```

Notes:
- `hello_contract.wasm`: compiled from example 1

**Comment by mentasuave01** [comment]
I strongly suggest using Ubuntu Binaries via WSL2 on windows.
Not only for Parallel but also for projects focus on Linux dev.

**Comment by aarangara** [comment]
I am using ubuntu and I am getting exactly the same error

**Comment by rnnz** [comment]
> I strongly suggest using Ubuntu Binaries via WSL2 on windows. Not only for Parallel but also for projects focus on Linux dev.

It works for me on Ubuntu, but as ParallelChain support windows sdk, I think it's worth to fix to attract more people joining testnet.

**Comment by mentasuave01** [comment]
> I am using ubuntu and I am getting exactly the same error - I also compiled the same example 1 code

If you don't provide the error it's near impossible to debug, could you copy the error message?

**Comment by mentasuave01** [comment]
> I am using ubuntu and I am getting exactly the same error - I also compiled the same example 1 code

Error code 1 means no gas, did you have enough tokens to cover the deploy of the contract?

**Comment by parallelchainlab** [comment]
> Command:
> pchain.exe submit tx --from-address pxSk6-3pl_yOFe95bwLDuETle8unlR6971A6SwqO3hI --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data "./hello_contract.wasm" --nonce 1 --path-to-keypair-json ./keypair.json

The executable you used should be the old version one that used in testnet 2.

Please use the latest binaries of `pchain_client`, and update the endpoints for testnet 3:
```
standard_api_url is https://node-t3-1.digital-transaction.net/
rich_api_url is https://service-t3.digital-transaction.net/rich_api
analytics_api_url is https://service-t3.digital-transaction.net/analytics_api
```

**Comment by parallelchainlab** [comment]
> I am using ubuntu and I am getting exactly the same error - I also compiled the same example 1 code

FYI, successful transaction submission should report status code `202`. 
```
Status 202
Response "Transaction Added to mempool"
```

Common failure reasons:
- Incorrect endpoints
- Insufficient balance 
- Incorrect nonce
- The provided gas limit is not enough

**Comment by rnnz** [comment]
It worked with pchain v3. Thanks!

Linked issue: https://github.com/parallelchain-io/pchain-sdk/issues/6
