### ISSUE TITLE
[Ubuntu] Query a smart contract code: 404 Not Found

### ISSUE THREAD

**Issue by rnnz** [parallelchain-io/pchain-sdk#8]
Environment: Ubuntu
Wallet: pZontzxjrrcIVJID7guwAia_WJnVLnubJUHPxLso7KI (1,000,000 TXPLL)

How to produce the error:
- Deploy a contract: 
`./pchain submit tx --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data "./hello_contract.wasm" --nonce 1 --keypair-name mykey.json`

- Output:
```
Contract address: "fX6H9EqnjEDD14AQV2SgyD7fXKNUl9ffVH4onGrPmsA"
Signature of tx: "bB_YSycH7m5LgVGD5X4RJoORJ-5wHPHp2qa2meTiojShRsO5HpI14eNDS9BrUHsPvpfXe-mTZqLqWyon0esHDQ"
Hash of tx: "WG4guRUTat6Y3HQq3xSUsXptGfWVvaS1-P0L6-ncpvI"
Submit Transaction {
  "to_address": "null",
  "value": 0,
  "tip": 0,
  "gas_limit": 10000000,
  "gas_price": 1,
  "data": "./hello_contract.wasm",
  "deploy_args": "",
  "nonce": 1,
  "keypair_name": "mykey.json"
}
Status 202
Response "Transaction Added to mempool"
```

- **Query contract code**:
`./pchain query account contract-code --address fX6H9EqnjEDD14AQV2SgyD7fXKNUl9ffVH4onGrPmsA`

- **Error output**: (no error detail)
```
Query Error. Status: 404 Not Found
Query Error. Detail:
```

**Comment by parallelchainlab** [comment]
You can check your transaction status by following command:
```sh
./pchain_client query txs --tx-hash <TX_HASH> --order asc
```
If your transaction is not found, it is possibly still pending to execute in Mempool.

You can check transaction in Mempool by following command: 
```sh
./pchain_client query mempool info --tx-hash <TX_HASH>
```
The result shows that your transaction was not being executed and dropped after timeout in Mempool.
```
Info of Transaction in Mempool:
TxMempoolInfo { location: "DROPPED TRANSACTIONS DATABASE", status: "The Transaction is expired and has been dropped by the mempool.", transaction: Transaction { from_address: "pZontzxjrrcIVJID7guwAia_WJnVLnubJUHPxLso7KI", to_address: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", value: 0, tip: 0, gas_limit: 10000000, gas_price: 1, data: "PIoAAABhc20BAAAAAWgQYAJ_fwF_YAJ_fwBgA39_fwF_YAF_AX9gAX8AYAN_f38AYAR_f39_AGAAAGABfwF-YAR_f39_AX9gBX9_f39_AGADf39_AX5gBn9_f39_fwF_YAd_f39_f39 .....
```

One possible failure reason is that your transaction is submitted with incorrect nonce. (the value of nonce starts from 0) 

You can check your account current nonce by following command.
```
./pchain_client query account nonce --address <YOUR_ACCOUNT_ADDRESS>
```

**Comment by rnnz** [comment]
I had to pass "deploy_args" and it worked. Thanks!
