### ISSUE TITLE
Contract verificator didn't work

### ISSUE THREAD

**Issue by mentasuave01** [parallelchain-io/pchain-sdk#9]
Input

```sh

 ./pchain_client submit tx --to-address null --value 0 --tip 0 --gas-limit 10000000 --gas-price 1 --data ./hello_contract.wasm --deploy-args null --nonce 0 --keypair-name Paco
Contract address: "gvNZldGE94V_BVvoN00KlQZc4gObUwEIkEGQp5igLrY"
Signature of tx: "0obfRAVQJ8sLbUFg59v11LxPSGlyuGHTgegA3f44PzhI8Pyj2pIMFRkzMg_2Jr0TlfrXnxvPwlW_vcyvm_mzAQ"
Hash of tx: "lU3xo8Ap8lQtk5uyc9rgr0viLMI9YcDbPzix0NO4HFA"
Submit Transaction {
  "to_address": "null",
  "value": 0,
  "tip": 0,
  "gas_limit": 10000000,
  "gas_price": 1,
  "data": "./hello_contract.wasm",
  "deploy_args": "null",
  "nonce": 0,
  "keypair_name": "Paco"
}
Status 202
Response "Transaction Added to mempool"
```

Error: The transaction receipt status code was not success. Please provide correct tx_hash or re-deploy your smart contract.

**Comment by parallelchainlab** [comment]
Thanks for your comment. There was an error in execution of `Init` method of your deploying contract.

Receipt of the transaction [lU3xo8Ap8lQtk5uyc9rgr0viLMI9YcDbPzix0NO4HFA](https://testnet.parallelchain.io/explorer/transactions/details?transaction_hash=lU3xo8Ap8lQtk5uyc9rgr0viLMI9YcDbPzix0NO4HFA) reports error code as `31`. It is [Runtime Error](https://docs.parallelchain.io/getting_started/status_code/) which indicates failure in contract execution. 

Observed that your contract is called "hello_contract.wasm", we assume your deploying contract is taking from [tutorial - chapter 1](https://github.com/parallelchain-io/example-smart-contracts).

The contract contains an `Init` Method that is **required** to be executed when deployment. 
```rust
#[init]
    fn new(hello_msg : String) {
```
The method takes an argument (a String) but you did not provide argument in the submit transaction. 
```json
"deploy_args": "null"
```
It is the reason why it fails to execute the `Init` method.

### Solution

For the field "deploy_args", please use `pchain_client` to generate input according to your method argument. For example, if you want to input String "hello" to `hello_msg`, in your `call_data.json`:
```json
{
    "method_name": "",
    "arguments": {
        { "type": "String", "value": "hello" }
    }
}
```
Run command:
```sh
./pchain parse calldata --json-file call_data.json
```
The output shows a Base64 URL encoded string that can be used for the field, i.e.
```json
"deploy_args": "AAAAAAAAAAARAAAAAQAAAAkAAAAFAAAAaGVsbG8"
```


### About Contract Methods
Please find the documentation about details of `Init` Method, as well as `Action` and `View` Methods on [README.md](https://github.com/parallelchain-io/pchain-sdk/blob/main/README.md)

**Comment by mentasuave01** [comment]
Okay all set and clear, thanks for the fast response.
